In [1]:
import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv('weight-height.csv')

In [3]:
df.head()

Gender     Height      Weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [4]:
df.isnull().sum()

Gender    0
Height    0
Weight    0
dtype: int64

In [5]:
df.shape

(8555, 3)

# Apply Encoding

In [6]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [7]:
df.Gender=le.fit_transform(df.Gender)

In [8]:
df.head(1)

Gender     Height      Weight
0       1  73.847017  241.893563

In [9]:
df.tail(2)

Gender     Height      Weight
8553       0  67.429971  151.678405
8554       0  60.921791  131.253738

In [10]:
x=df.drop('Weight',axis=1)
x.head(1)

Gender     Height
0       1  73.847017

In [11]:
y=df['Weight']
y.head(1)

0    241.893563
Name: Weight, dtype: float64

# Spliting train and test

In [12]:
from sklearn.model_selection import train_test_split
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=.30,random_state=1)

In [13]:
xtrain.shape

(5988, 2)

In [23]:
xtest.shape

(2567, 2)

# Linear Regression

In [15]:
from sklearn.linear_model import LinearRegression   #Linear Regression
reg  = LinearRegression() #create linear reg object
reg.fit(xtrain,ytrain)

LinearRegression()

In [16]:
reg.coef_   # coefficient in linear regression

array([19.34359322,  5.96887438])

In [17]:
reg.intercept_  # value of intercept

-244.5528090325578

In [18]:
reg.predict(xtest)

array([143.83013436, 197.53417989, 184.63515112, ..., 160.7078525 ,
       186.82852694, 201.4226542 ])

In [19]:
pred = reg.predict(xtest)

In [21]:
#Model Evaluation
from sklearn.metrics import mean_squared_error, r2_score
mean_squared_error(ytest, pred)

99.67250998070031

In [22]:
r2_score(ytest,pred)

0.905995960709116

# KNN Regressor

In [24]:
from sklearn.neighbors import KNeighborsRegressor
knn= KNeighborsRegressor(n_neighbors=100)   #For 100 we are taking 5
knn.fit(xtrain,ytrain)

KNeighborsRegressor(n_neighbors=100)

In [25]:
predic1=knn.predict(xtest)
predic1

array([142.83375838, 198.29567688, 185.1495741 , ..., 159.8721488 ,
       185.95631787, 201.0705108 ])

In [27]:
mean_squared_error(ytest,predic1)

104.01856360504236

In [29]:
r2_score(ytest,predic1)

0.9018970712987657

# From accuracy ,it is stated that Linrear regression is slightly better compare then KNN Regressor